using System.Text.Json.Serialization;

namespace PromptEngineering.LLM.Models;

public record ChatCompletionChoice
{
    /// <summary>
    /// The index of the choice in the list of choices.
    /// </summary>
    [JsonPropertyName("index")]
    public int? Index { get; set; }

    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public ChatMessage? Message { get; set; }

    /// <summary>
    /// Gets or sets the incremental content of the chat message as provided in the current response segment.
    /// Used when streaming responses.
    /// </summary>
    /// <remarks>This property typically contains only the portion of the message that is new or changed since
    /// the previous response. It may be null if no incremental content is present.</remarks>
    [JsonPropertyName("delta")]
    public DeltaMessage? Delta { get; set; }

    /// <summary>
    /// The reason the model stopped generating tokens. This will be stop if the model
    /// hit a natural stop point or a provided stop sequence, length if the maximum number
    /// of tokens specified in the request was reached, content_filter if content was
    /// omitted due to a flag from our content filters, tool_calls if the model called a tool,
    /// or function_call (deprecated) if the model called a function.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public FinishReason? FinishReason { get; set; }
}
