<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.Authentication.Msal" Version="1.*" />
    <PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PromptEngineering.LLM\PromptEngineering.LLM.csproj" />
    <ProjectReference Include="..\PromptEngineering.Mcp\PromptEngineering.Mcp.csproj" />
  </ItemGroup>

</Project>
